chore: ignore .terraform folder and tfstate files

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -15,19 +15,17 @@ jobs:
       - name: 🛎️ Checkout code
         uses: actions/checkout@v4
 
-      - name: 🔑 Install SSH Key
-        uses: shimataro/ssh-key-action@v2
-        with:
-          key: ${{ secrets.EC2_SSH_KEY }}
-          name: id_rsa
-          known_hosts: unnecessary
+      - name: Create SSH Key
+	run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
 
       - name: 🚀 Deploy to EC2
         run: |
-          chmod 600 id_rsa
-          ssh -o StrictHostKeyChecking=no -i id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
+          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@${{ secrets.EC2_PUBLIC_IP }} '
             echo "🔄 Pulling latest code..."
-            cd /home/ubuntu/my-vue-app || { echo "❌ App directory not found"; exit 1; }
+            cd /home/ubuntu/aaniraikaaththal || { echo "❌ App directory not found"; exit 1; }
             git fetch origin main
             git reset --hard origin/main
 
